**Numpy** in short numerical python is library used for scientific computation, it provides tools to work with multi dimensional arrays and matrices.

In [1]:
import numpy as np
print(np.__version__)

2.2.6


In [2]:
arr = np.array([1,2,3,4,5,6]) #1d array
print(arr)

[1 2 3 4 5 6]


In [3]:
arr1 = np.array(42) #0d array
print(arr1)
arr2  = np.array([1,2,3,4,5]) #1d array
print(arr2)
arr3 = np.array([[1,2,3],[4,5,6]]) #2d array
print(arr3)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


we use **ndim** function to get the dimension of the array, similarly we can define the dimensions that we want to create the array

In [9]:
print(arr3.ndim)
arr4 = np.array([1,2,3,4], ndmin = 5)
print(arr4.ndim,arr4)

2
5 [[[[[1 2 3 4]]]]]


In [15]:
arr5 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr5[0,1])
print(arr5[1,0])
print(arr5[0,1,2])
print(arr5[1,1,1])

[4 5 6]
[7 8 9]
6
11


Slicing the array in python

In [16]:
arr6 = np.array([1,2,3,4,5,6,7])
print(arr6[1:5])
print(arr6[:4])
print(arr6[4:])
print(arr6[-3:-1])
print(arr6[1:5:2])
print(arr6[::2])

[2 3 4 5]
[1 2 3 4]
[5 6 7]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2]) # here for columns it will pick single index 2 from row 0 and row1
print(arr[0:2,1:3]) # here 0:2 is for rows and 1:3 is for columns

[3 8]
[[2 3]
 [7 8]]


array operations using numpy

In [19]:
arr1 = np.array([[1,2],[4,5]])
arr2 = np.array([[5,6],[7,8]])
arr5 = np.concatenate((arr1,arr2),axis= 1)
print(arr5)

[[1 2 5 6]
 [4 5 7 8]]


In [24]:
arr6 = np.array([1,2,3,4,5])
arr7 = np.array_split(arr6,3) # splits the array into 3 parts
print(arr7)

[array([1, 2]), array([3, 4]), array([5])]


In [25]:
print(arr7[0])
print(arr7[0][1])

[1 2]
2
